# Populates pages with self-contained HTML
pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir public
    - cd docs
    - cp appendix.html index.html
    - mv index.html ../public # copy index to update
  artifacts:
    paths:
      - public
    expire_in: 15 mins
  only:
    - tags
